#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyNhanSu_Hai.DataAccess
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyNhanSu_Hai")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertTrinhDoChuyenMon(TrinhDoChuyenMon instance);
    partial void UpdateTrinhDoChuyenMon(TrinhDoChuyenMon instance);
    partial void DeleteTrinhDoChuyenMon(TrinhDoChuyenMon instance);
    partial void InsertDanToc(DanToc instance);
    partial void UpdateDanToc(DanToc instance);
    partial void DeleteDanToc(DanToc instance);
    partial void InsertHeThong(HeThong instance);
    partial void UpdateHeThong(HeThong instance);
    partial void DeleteHeThong(HeThong instance);
    partial void InsertHocHam(HocHam instance);
    partial void UpdateHocHam(HocHam instance);
    partial void DeleteHocHam(HocHam instance);
    partial void InsertHopDongLaoDong(HopDongLaoDong instance);
    partial void UpdateHopDongLaoDong(HopDongLaoDong instance);
    partial void DeleteHopDongLaoDong(HopDongLaoDong instance);
    partial void InsertHoSoCanBo(HoSoCanBo instance);
    partial void UpdateHoSoCanBo(HoSoCanBo instance);
    partial void DeleteHoSoCanBo(HoSoCanBo instance);
    partial void InsertKhenThuong(KhenThuong instance);
    partial void UpdateKhenThuong(KhenThuong instance);
    partial void DeleteKhenThuong(KhenThuong instance);
    partial void InsertKyLuat(KyLuat instance);
    partial void UpdateKyLuat(KyLuat instance);
    partial void DeleteKyLuat(KyLuat instance);
    partial void InsertLuong(Luong instance);
    partial void UpdateLuong(Luong instance);
    partial void DeleteLuong(Luong instance);
    partial void InsertNgoaiNgu(NgoaiNgu instance);
    partial void UpdateNgoaiNgu(NgoaiNgu instance);
    partial void DeleteNgoaiNgu(NgoaiNgu instance);
    partial void InsertQuanHeGiaDinh(QuanHeGiaDinh instance);
    partial void UpdateQuanHeGiaDinh(QuanHeGiaDinh instance);
    partial void DeleteQuanHeGiaDinh(QuanHeGiaDinh instance);
    partial void InsertQuaTrinhCongTac(QuaTrinhCongTac instance);
    partial void UpdateQuaTrinhCongTac(QuaTrinhCongTac instance);
    partial void DeleteQuaTrinhCongTac(QuaTrinhCongTac instance);
    partial void InsertThamNien(ThamNien instance);
    partial void UpdateThamNien(ThamNien instance);
    partial void DeleteThamNien(ThamNien instance);
    partial void InsertTo(To instance);
    partial void UpdateTo(To instance);
    partial void DeleteTo(To instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::QuanLyNhanSu_Hai.Properties.Settings.Default.QuanLyNhanSu_HaiConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<TrinhDoChuyenMon> TrinhDoChuyenMons
		{
			get
			{
				return this.GetTable<TrinhDoChuyenMon>();
			}
		}
		
		public System.Data.Linq.Table<DanToc> DanTocs
		{
			get
			{
				return this.GetTable<DanToc>();
			}
		}
		
		public System.Data.Linq.Table<HeThong> HeThongs
		{
			get
			{
				return this.GetTable<HeThong>();
			}
		}
		
		public System.Data.Linq.Table<HocHam> HocHams
		{
			get
			{
				return this.GetTable<HocHam>();
			}
		}
		
		public System.Data.Linq.Table<HopDongLaoDong> HopDongLaoDongs
		{
			get
			{
				return this.GetTable<HopDongLaoDong>();
			}
		}
		
		public System.Data.Linq.Table<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this.GetTable<HoSoCanBo>();
			}
		}
		
		public System.Data.Linq.Table<KhenThuong> KhenThuongs
		{
			get
			{
				return this.GetTable<KhenThuong>();
			}
		}
		
		public System.Data.Linq.Table<KyLuat> KyLuats
		{
			get
			{
				return this.GetTable<KyLuat>();
			}
		}
		
		public System.Data.Linq.Table<Luong> Luongs
		{
			get
			{
				return this.GetTable<Luong>();
			}
		}
		
		public System.Data.Linq.Table<NgoaiNgu> NgoaiNgus
		{
			get
			{
				return this.GetTable<NgoaiNgu>();
			}
		}
		
		public System.Data.Linq.Table<QuanHeGiaDinh> QuanHeGiaDinhs
		{
			get
			{
				return this.GetTable<QuanHeGiaDinh>();
			}
		}
		
		public System.Data.Linq.Table<QuaTrinhCongTac> QuaTrinhCongTacs
		{
			get
			{
				return this.GetTable<QuaTrinhCongTac>();
			}
		}
		
		public System.Data.Linq.Table<ThamNien> ThamNiens
		{
			get
			{
				return this.GetTable<ThamNien>();
			}
		}
		
		public System.Data.Linq.Table<To> Tos
		{
			get
			{
				return this.GetTable<To>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCV;
		
		private string _TenChucVu;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnTenChucVuChanging(string value);
    partial void OnTenChucVuChanged();
    #endregion
		
		public ChucVu()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChucVu", DbType="NVarChar(50)")]
		public string TenChucVu
		{
			get
			{
				return this._TenChucVu;
			}
			set
			{
				if ((this._TenChucVu != value))
				{
					this.OnTenChucVuChanging(value);
					this.SendPropertyChanging();
					this._TenChucVu = value;
					this.SendPropertyChanged("TenChucVu");
					this.OnTenChucVuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaCV", OtherKey="MaCV")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TrinhDoChuyenMon")]
	public partial class TrinhDoChuyenMon : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTDCM;
		
		private string _NganhDT;
		
		private string _LoaiHinhDT;
		
		private string _TruongDT;
		
		private string _NienKhoa;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDCMChanging(string value);
    partial void OnMaTDCMChanged();
    partial void OnNganhDTChanging(string value);
    partial void OnNganhDTChanged();
    partial void OnLoaiHinhDTChanging(string value);
    partial void OnLoaiHinhDTChanged();
    partial void OnTruongDTChanging(string value);
    partial void OnTruongDTChanged();
    partial void OnNienKhoaChanging(string value);
    partial void OnNienKhoaChanged();
    #endregion
		
		public TrinhDoChuyenMon()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTDCM", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTDCM
		{
			get
			{
				return this._MaTDCM;
			}
			set
			{
				if ((this._MaTDCM != value))
				{
					this.OnMaTDCMChanging(value);
					this.SendPropertyChanging();
					this._MaTDCM = value;
					this.SendPropertyChanged("MaTDCM");
					this.OnMaTDCMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NganhDT", DbType="NVarChar(50)")]
		public string NganhDT
		{
			get
			{
				return this._NganhDT;
			}
			set
			{
				if ((this._NganhDT != value))
				{
					this.OnNganhDTChanging(value);
					this.SendPropertyChanging();
					this._NganhDT = value;
					this.SendPropertyChanged("NganhDT");
					this.OnNganhDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHinhDT", DbType="NVarChar(50)")]
		public string LoaiHinhDT
		{
			get
			{
				return this._LoaiHinhDT;
			}
			set
			{
				if ((this._LoaiHinhDT != value))
				{
					this.OnLoaiHinhDTChanging(value);
					this.SendPropertyChanging();
					this._LoaiHinhDT = value;
					this.SendPropertyChanged("LoaiHinhDT");
					this.OnLoaiHinhDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TruongDT", DbType="NVarChar(50)")]
		public string TruongDT
		{
			get
			{
				return this._TruongDT;
			}
			set
			{
				if ((this._TruongDT != value))
				{
					this.OnTruongDTChanging(value);
					this.SendPropertyChanging();
					this._TruongDT = value;
					this.SendPropertyChanged("TruongDT");
					this.OnTruongDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NienKhoa", DbType="NVarChar(10)")]
		public string NienKhoa
		{
			get
			{
				return this._NienKhoa;
			}
			set
			{
				if ((this._NienKhoa != value))
				{
					this.OnNienKhoaChanging(value);
					this.SendPropertyChanging();
					this._NienKhoa = value;
					this.SendPropertyChanged("NienKhoa");
					this.OnNienKhoaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDoChuyenMon_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaTDCM", OtherKey="MaTDCM")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDoChuyenMon = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.TrinhDoChuyenMon = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanToc")]
	public partial class DanToc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _DanToc1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnDanToc1Changing(string value);
    partial void OnDanToc1Changed();
    #endregion
		
		public DanToc()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="DanToc", Storage="_DanToc1", DbType="NVarChar(50)")]
		public string DanToc1
		{
			get
			{
				return this._DanToc1;
			}
			set
			{
				if ((this._DanToc1 != value))
				{
					this.OnDanToc1Changing(value);
					this.SendPropertyChanging();
					this._DanToc1 = value;
					this.SendPropertyChanged("DanToc1");
					this.OnDanToc1Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HeThong")]
	public partial class HeThong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Username;
		
		private string _Password;
		
		private System.Nullable<bool> _Access;
		
		private System.Nullable<bool> _Update;
		
		private System.Nullable<bool> _Manage;
		
		private string _Discription;
		
		private string _FullName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnAccessChanging(System.Nullable<bool> value);
    partial void OnAccessChanged();
    partial void OnUpdateChanging(System.Nullable<bool> value);
    partial void OnUpdateChanged();
    partial void OnManageChanging(System.Nullable<bool> value);
    partial void OnManageChanged();
    partial void OnDiscriptionChanging(string value);
    partial void OnDiscriptionChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    #endregion
		
		public HeThong()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(25) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(8)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Access", DbType="Bit")]
		public System.Nullable<bool> Access
		{
			get
			{
				return this._Access;
			}
			set
			{
				if ((this._Access != value))
				{
					this.OnAccessChanging(value);
					this.SendPropertyChanging();
					this._Access = value;
					this.SendPropertyChanged("Access");
					this.OnAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Update]", Storage="_Update", DbType="Bit")]
		public System.Nullable<bool> Update
		{
			get
			{
				return this._Update;
			}
			set
			{
				if ((this._Update != value))
				{
					this.OnUpdateChanging(value);
					this.SendPropertyChanging();
					this._Update = value;
					this.SendPropertyChanged("Update");
					this.OnUpdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Manage", DbType="Bit")]
		public System.Nullable<bool> Manage
		{
			get
			{
				return this._Manage;
			}
			set
			{
				if ((this._Manage != value))
				{
					this.OnManageChanging(value);
					this.SendPropertyChanging();
					this._Manage = value;
					this.SendPropertyChanged("Manage");
					this.OnManageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discription", DbType="NVarChar(30)")]
		public string Discription
		{
			get
			{
				return this._Discription;
			}
			set
			{
				if ((this._Discription != value))
				{
					this.OnDiscriptionChanging(value);
					this.SendPropertyChanging();
					this._Discription = value;
					this.SendPropertyChanged("Discription");
					this.OnDiscriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(50)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HocHam")]
	public partial class HocHam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaHocHam;
		
		private string _HocHam1;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaHocHamChanging(string value);
    partial void OnMaHocHamChanged();
    partial void OnHocHam1Changing(string value);
    partial void OnHocHam1Changed();
    #endregion
		
		public HocHam()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocHam", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaHocHam
		{
			get
			{
				return this._MaHocHam;
			}
			set
			{
				if ((this._MaHocHam != value))
				{
					this.OnMaHocHamChanging(value);
					this.SendPropertyChanging();
					this._MaHocHam = value;
					this.SendPropertyChanged("MaHocHam");
					this.OnMaHocHamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="HocHam", Storage="_HocHam1", DbType="NVarChar(50)")]
		public string HocHam1
		{
			get
			{
				return this._HocHam1;
			}
			set
			{
				if ((this._HocHam1 != value))
				{
					this.OnHocHam1Changing(value);
					this.SendPropertyChanging();
					this._HocHam1 = value;
					this.SendPropertyChanged("HocHam1");
					this.OnHocHam1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocHam_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaHocHam", OtherKey="MaHocHam")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.HocHam = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.HocHam = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HopDongLaoDong")]
	public partial class HopDongLaoDong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MasoHD;
		
		private System.Nullable<System.DateTime> _NgayHD;
		
		private string _LoaiHD;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private System.Nullable<System.DateTime> _NgayXL;
		
		private string _SoBHYT;
		
		private string _SoBHXH;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMasoHDChanging(string value);
    partial void OnMasoHDChanged();
    partial void OnNgayHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHDChanged();
    partial void OnLoaiHDChanging(string value);
    partial void OnLoaiHDChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnNgayXLChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXLChanged();
    partial void OnSoBHYTChanging(string value);
    partial void OnSoBHYTChanged();
    partial void OnSoBHXHChanging(string value);
    partial void OnSoBHXHChanged();
    #endregion
		
		public HopDongLaoDong()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasoHD", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MasoHD
		{
			get
			{
				return this._MasoHD;
			}
			set
			{
				if ((this._MasoHD != value))
				{
					this.OnMasoHDChanging(value);
					this.SendPropertyChanging();
					this._MasoHD = value;
					this.SendPropertyChanged("MasoHD");
					this.OnMasoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayHD
		{
			get
			{
				return this._NgayHD;
			}
			set
			{
				if ((this._NgayHD != value))
				{
					this.OnNgayHDChanging(value);
					this.SendPropertyChanging();
					this._NgayHD = value;
					this.SendPropertyChanged("NgayHD");
					this.OnNgayHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHD", DbType="NVarChar(50)")]
		public string LoaiHD
		{
			get
			{
				return this._LoaiHD;
			}
			set
			{
				if ((this._LoaiHD != value))
				{
					this.OnLoaiHDChanging(value);
					this.SendPropertyChanging();
					this._LoaiHD = value;
					this.SendPropertyChanged("LoaiHD");
					this.OnLoaiHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXL", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayXL
		{
			get
			{
				return this._NgayXL;
			}
			set
			{
				if ((this._NgayXL != value))
				{
					this.OnNgayXLChanging(value);
					this.SendPropertyChanging();
					this._NgayXL = value;
					this.SendPropertyChanged("NgayXL");
					this.OnNgayXLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHYT", DbType="NVarChar(9)")]
		public string SoBHYT
		{
			get
			{
				return this._SoBHYT;
			}
			set
			{
				if ((this._SoBHYT != value))
				{
					this.OnSoBHYTChanging(value);
					this.SendPropertyChanging();
					this._SoBHYT = value;
					this.SendPropertyChanged("SoBHYT");
					this.OnSoBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHXH", DbType="NVarChar(9)")]
		public string SoBHXH
		{
			get
			{
				return this._SoBHXH;
			}
			set
			{
				if ((this._SoBHXH != value))
				{
					this.OnSoBHXHChanging(value);
					this.SendPropertyChanging();
					this._SoBHXH = value;
					this.SendPropertyChanged("SoBHXH");
					this.OnSoBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDongLaoDong_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MasoHD", OtherKey="MasoHD")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.HopDongLaoDong = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.HopDongLaoDong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoSoCanBo")]
	public partial class HoSoCanBo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaCB;
		
		private string _HoTen;
		
		private string _GioiTinh;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _Noisinh;
		
		private string _QueQuan;
		
		private string _DanToc;
		
		private string _MaTN;
		
		private string _MaCV;
		
		private System.Nullable<System.DateTime> _NgayChuyenCT;
		
		private string _QuaTrinhCongTac;
		
		private string _MaTo;
		
		private string _MaTDCM;
		
		private string _SoCMND;
		
		private System.Nullable<System.DateTime> _NgayCap;
		
		private string _NoiCap;
		
		private string _DiaChi;
		
		private string _SoDT;
		
		private System.Nullable<bool> _DangVien;
		
		private string _SoTheDang;
		
		private System.Nullable<System.DateTime> _NgayVaoDang;
		
		private string _NoiVaoDang;
		
		private string _MaTDNN;
		
		private string _MaHocHam;
		
		private System.Nullable<System.DateTime> _NgayNhanHH;
		
		private string _MaLuong;
		
		private string _MasoHD;
		
		private string _LoaiHD;
		
		private System.Nullable<System.DateTime> _NgayHD;
		
		private System.Nullable<System.DateTime> _NgayBD;
		
		private System.Nullable<System.DateTime> _NgayKT;
		
		private System.Nullable<System.DateTime> _NgayXL;
		
		private string _SoBHXH;
		
		private string _SoBHYT;
		
		private System.Nullable<double> _LuongTL;
		
		private string _ThueTN;
		
		private EntitySet<KhenThuong> _KhenThuongs;
		
		private EntitySet<KyLuat> _KyLuats;
		
		private EntitySet<QuanHeGiaDinh> _QuanHeGiaDinhs;
		
		private EntitySet<QuaTrinhCongTac> _QuaTrinhCongTacs;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<HocHam> _HocHam;
		
		private EntityRef<HopDongLaoDong> _HopDongLaoDong;
		
		private EntityRef<TrinhDoChuyenMon> _TrinhDoChuyenMon;
		
		private EntityRef<Luong> _Luong;
		
		private EntityRef<NgoaiNgu> _NgoaiNgu;
		
		private EntityRef<ThamNien> _ThamNien;
		
		private EntityRef<To> _To;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnGioiTinhChanging(string value);
    partial void OnGioiTinhChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNoisinhChanging(string value);
    partial void OnNoisinhChanged();
    partial void OnQueQuanChanging(string value);
    partial void OnQueQuanChanged();
    partial void OnDanTocChanging(string value);
    partial void OnDanTocChanged();
    partial void OnMaTNChanging(string value);
    partial void OnMaTNChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnNgayChuyenCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenCTChanged();
    partial void OnQuaTrinhCongTacChanging(string value);
    partial void OnQuaTrinhCongTacChanged();
    partial void OnMaToChanging(string value);
    partial void OnMaToChanged();
    partial void OnMaTDCMChanging(string value);
    partial void OnMaTDCMChanged();
    partial void OnSoCMNDChanging(string value);
    partial void OnSoCMNDChanged();
    partial void OnNgayCapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayCapChanged();
    partial void OnNoiCapChanging(string value);
    partial void OnNoiCapChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnSoDTChanging(string value);
    partial void OnSoDTChanged();
    partial void OnDangVienChanging(System.Nullable<bool> value);
    partial void OnDangVienChanged();
    partial void OnSoTheDangChanging(string value);
    partial void OnSoTheDangChanged();
    partial void OnNgayVaoDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayVaoDangChanged();
    partial void OnNoiVaoDangChanging(string value);
    partial void OnNoiVaoDangChanged();
    partial void OnMaTDNNChanging(string value);
    partial void OnMaTDNNChanged();
    partial void OnMaHocHamChanging(string value);
    partial void OnMaHocHamChanged();
    partial void OnNgayNhanHHChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhanHHChanged();
    partial void OnMaLuongChanging(string value);
    partial void OnMaLuongChanged();
    partial void OnMasoHDChanging(string value);
    partial void OnMasoHDChanged();
    partial void OnLoaiHDChanging(string value);
    partial void OnLoaiHDChanged();
    partial void OnNgayHDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayHDChanged();
    partial void OnNgayBDChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDChanged();
    partial void OnNgayKTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTChanged();
    partial void OnNgayXLChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayXLChanged();
    partial void OnSoBHXHChanging(string value);
    partial void OnSoBHXHChanged();
    partial void OnSoBHYTChanging(string value);
    partial void OnSoBHYTChanged();
    partial void OnLuongTLChanging(System.Nullable<double> value);
    partial void OnLuongTLChanged();
    partial void OnThueTNChanging(string value);
    partial void OnThueTNChanged();
    #endregion
		
		public HoSoCanBo()
		{
			this._KhenThuongs = new EntitySet<KhenThuong>(new Action<KhenThuong>(this.attach_KhenThuongs), new Action<KhenThuong>(this.detach_KhenThuongs));
			this._KyLuats = new EntitySet<KyLuat>(new Action<KyLuat>(this.attach_KyLuats), new Action<KyLuat>(this.detach_KyLuats));
			this._QuanHeGiaDinhs = new EntitySet<QuanHeGiaDinh>(new Action<QuanHeGiaDinh>(this.attach_QuanHeGiaDinhs), new Action<QuanHeGiaDinh>(this.detach_QuanHeGiaDinhs));
			this._QuaTrinhCongTacs = new EntitySet<QuaTrinhCongTac>(new Action<QuaTrinhCongTac>(this.attach_QuaTrinhCongTacs), new Action<QuaTrinhCongTac>(this.detach_QuaTrinhCongTacs));
			this._ChucVu = default(EntityRef<ChucVu>);
			this._HocHam = default(EntityRef<HocHam>);
			this._HopDongLaoDong = default(EntityRef<HopDongLaoDong>);
			this._TrinhDoChuyenMon = default(EntityRef<TrinhDoChuyenMon>);
			this._Luong = default(EntityRef<Luong>);
			this._NgoaiNgu = default(EntityRef<NgoaiNgu>);
			this._ThamNien = default(EntityRef<ThamNien>);
			this._To = default(EntityRef<To>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="NVarChar(5)")]
		public string GioiTinh
		{
			get
			{
				return this._GioiTinh;
			}
			set
			{
				if ((this._GioiTinh != value))
				{
					this.OnGioiTinhChanging(value);
					this.SendPropertyChanging();
					this._GioiTinh = value;
					this.SendPropertyChanged("GioiTinh");
					this.OnGioiTinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noisinh", DbType="NVarChar(50)")]
		public string Noisinh
		{
			get
			{
				return this._Noisinh;
			}
			set
			{
				if ((this._Noisinh != value))
				{
					this.OnNoisinhChanging(value);
					this.SendPropertyChanging();
					this._Noisinh = value;
					this.SendPropertyChanged("Noisinh");
					this.OnNoisinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueQuan", DbType="NVarChar(50)")]
		public string QueQuan
		{
			get
			{
				return this._QueQuan;
			}
			set
			{
				if ((this._QueQuan != value))
				{
					this.OnQueQuanChanging(value);
					this.SendPropertyChanging();
					this._QueQuan = value;
					this.SendPropertyChanged("QueQuan");
					this.OnQueQuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DanToc", DbType="NVarChar(20)")]
		public string DanToc
		{
			get
			{
				return this._DanToc;
			}
			set
			{
				if ((this._DanToc != value))
				{
					this.OnDanTocChanging(value);
					this.SendPropertyChanging();
					this._DanToc = value;
					this.SendPropertyChanged("DanToc");
					this.OnDanTocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTN", DbType="VarChar(15)")]
		public string MaTN
		{
			get
			{
				return this._MaTN;
			}
			set
			{
				if ((this._MaTN != value))
				{
					if (this._ThamNien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTNChanging(value);
					this.SendPropertyChanging();
					this._MaTN = value;
					this.SendPropertyChanged("MaTN");
					this.OnMaTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="VarChar(15)")]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenCT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayChuyenCT
		{
			get
			{
				return this._NgayChuyenCT;
			}
			set
			{
				if ((this._NgayChuyenCT != value))
				{
					this.OnNgayChuyenCTChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenCT = value;
					this.SendPropertyChanged("NgayChuyenCT");
					this.OnNgayChuyenCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuaTrinhCongTac", DbType="NVarChar(250)")]
		public string QuaTrinhCongTac
		{
			get
			{
				return this._QuaTrinhCongTac;
			}
			set
			{
				if ((this._QuaTrinhCongTac != value))
				{
					this.OnQuaTrinhCongTacChanging(value);
					this.SendPropertyChanging();
					this._QuaTrinhCongTac = value;
					this.SendPropertyChanged("QuaTrinhCongTac");
					this.OnQuaTrinhCongTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTo", DbType="VarChar(15)")]
		public string MaTo
		{
			get
			{
				return this._MaTo;
			}
			set
			{
				if ((this._MaTo != value))
				{
					if (this._To.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaToChanging(value);
					this.SendPropertyChanging();
					this._MaTo = value;
					this.SendPropertyChanged("MaTo");
					this.OnMaToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTDCM", DbType="VarChar(15)")]
		public string MaTDCM
		{
			get
			{
				return this._MaTDCM;
			}
			set
			{
				if ((this._MaTDCM != value))
				{
					if (this._TrinhDoChuyenMon.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDCMChanging(value);
					this.SendPropertyChanging();
					this._MaTDCM = value;
					this.SendPropertyChanged("MaTDCM");
					this.OnMaTDCMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoCMND", DbType="VarChar(15)")]
		public string SoCMND
		{
			get
			{
				return this._SoCMND;
			}
			set
			{
				if ((this._SoCMND != value))
				{
					this.OnSoCMNDChanging(value);
					this.SendPropertyChanging();
					this._SoCMND = value;
					this.SendPropertyChanged("SoCMND");
					this.OnSoCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayCap", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayCap
		{
			get
			{
				return this._NgayCap;
			}
			set
			{
				if ((this._NgayCap != value))
				{
					this.OnNgayCapChanging(value);
					this.SendPropertyChanging();
					this._NgayCap = value;
					this.SendPropertyChanged("NgayCap");
					this.OnNgayCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiCap", DbType="NVarChar(50)")]
		public string NoiCap
		{
			get
			{
				return this._NoiCap;
			}
			set
			{
				if ((this._NoiCap != value))
				{
					this.OnNoiCapChanging(value);
					this.SendPropertyChanging();
					this._NoiCap = value;
					this.SendPropertyChanged("NoiCap");
					this.OnNoiCapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDT", DbType="VarChar(20)")]
		public string SoDT
		{
			get
			{
				return this._SoDT;
			}
			set
			{
				if ((this._SoDT != value))
				{
					this.OnSoDTChanging(value);
					this.SendPropertyChanging();
					this._SoDT = value;
					this.SendPropertyChanged("SoDT");
					this.OnSoDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DangVien", DbType="Bit")]
		public System.Nullable<bool> DangVien
		{
			get
			{
				return this._DangVien;
			}
			set
			{
				if ((this._DangVien != value))
				{
					this.OnDangVienChanging(value);
					this.SendPropertyChanging();
					this._DangVien = value;
					this.SendPropertyChanged("DangVien");
					this.OnDangVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoTheDang", DbType="VarChar(15)")]
		public string SoTheDang
		{
			get
			{
				return this._SoTheDang;
			}
			set
			{
				if ((this._SoTheDang != value))
				{
					this.OnSoTheDangChanging(value);
					this.SendPropertyChanging();
					this._SoTheDang = value;
					this.SendPropertyChanged("SoTheDang");
					this.OnSoTheDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayVaoDang", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayVaoDang
		{
			get
			{
				return this._NgayVaoDang;
			}
			set
			{
				if ((this._NgayVaoDang != value))
				{
					this.OnNgayVaoDangChanging(value);
					this.SendPropertyChanging();
					this._NgayVaoDang = value;
					this.SendPropertyChanged("NgayVaoDang");
					this.OnNgayVaoDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiVaoDang", DbType="NVarChar(50)")]
		public string NoiVaoDang
		{
			get
			{
				return this._NoiVaoDang;
			}
			set
			{
				if ((this._NoiVaoDang != value))
				{
					this.OnNoiVaoDangChanging(value);
					this.SendPropertyChanging();
					this._NoiVaoDang = value;
					this.SendPropertyChanged("NoiVaoDang");
					this.OnNoiVaoDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTDNN", DbType="VarChar(15)")]
		public string MaTDNN
		{
			get
			{
				return this._MaTDNN;
			}
			set
			{
				if ((this._MaTDNN != value))
				{
					if (this._NgoaiNgu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTDNNChanging(value);
					this.SendPropertyChanging();
					this._MaTDNN = value;
					this.SendPropertyChanged("MaTDNN");
					this.OnMaTDNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaHocHam", DbType="VarChar(15)")]
		public string MaHocHam
		{
			get
			{
				return this._MaHocHam;
			}
			set
			{
				if ((this._MaHocHam != value))
				{
					if (this._HocHam.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaHocHamChanging(value);
					this.SendPropertyChanging();
					this._MaHocHam = value;
					this.SendPropertyChanged("MaHocHam");
					this.OnMaHocHamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhanHH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayNhanHH
		{
			get
			{
				return this._NgayNhanHH;
			}
			set
			{
				if ((this._NgayNhanHH != value))
				{
					this.OnNgayNhanHHChanging(value);
					this.SendPropertyChanging();
					this._NgayNhanHH = value;
					this.SendPropertyChanged("NgayNhanHH");
					this.OnNgayNhanHHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuong", DbType="VarChar(15)")]
		public string MaLuong
		{
			get
			{
				return this._MaLuong;
			}
			set
			{
				if ((this._MaLuong != value))
				{
					if (this._Luong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLuongChanging(value);
					this.SendPropertyChanging();
					this._MaLuong = value;
					this.SendPropertyChanged("MaLuong");
					this.OnMaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasoHD", DbType="VarChar(15)")]
		public string MasoHD
		{
			get
			{
				return this._MasoHD;
			}
			set
			{
				if ((this._MasoHD != value))
				{
					if (this._HopDongLaoDong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMasoHDChanging(value);
					this.SendPropertyChanging();
					this._MasoHD = value;
					this.SendPropertyChanged("MasoHD");
					this.OnMasoHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiHD", DbType="NVarChar(50)")]
		public string LoaiHD
		{
			get
			{
				return this._LoaiHD;
			}
			set
			{
				if ((this._LoaiHD != value))
				{
					this.OnLoaiHDChanging(value);
					this.SendPropertyChanging();
					this._LoaiHD = value;
					this.SendPropertyChanged("LoaiHD");
					this.OnLoaiHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayHD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayHD
		{
			get
			{
				return this._NgayHD;
			}
			set
			{
				if ((this._NgayHD != value))
				{
					this.OnNgayHDChanging(value);
					this.SendPropertyChanging();
					this._NgayHD = value;
					this.SendPropertyChanged("NgayHD");
					this.OnNgayHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBD", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayBD
		{
			get
			{
				return this._NgayBD;
			}
			set
			{
				if ((this._NgayBD != value))
				{
					this.OnNgayBDChanging(value);
					this.SendPropertyChanging();
					this._NgayBD = value;
					this.SendPropertyChanged("NgayBD");
					this.OnNgayBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayKT
		{
			get
			{
				return this._NgayKT;
			}
			set
			{
				if ((this._NgayKT != value))
				{
					this.OnNgayKTChanging(value);
					this.SendPropertyChanging();
					this._NgayKT = value;
					this.SendPropertyChanged("NgayKT");
					this.OnNgayKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayXL", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayXL
		{
			get
			{
				return this._NgayXL;
			}
			set
			{
				if ((this._NgayXL != value))
				{
					this.OnNgayXLChanging(value);
					this.SendPropertyChanging();
					this._NgayXL = value;
					this.SendPropertyChanged("NgayXL");
					this.OnNgayXLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHXH", DbType="NVarChar(9)")]
		public string SoBHXH
		{
			get
			{
				return this._SoBHXH;
			}
			set
			{
				if ((this._SoBHXH != value))
				{
					this.OnSoBHXHChanging(value);
					this.SendPropertyChanging();
					this._SoBHXH = value;
					this.SendPropertyChanged("SoBHXH");
					this.OnSoBHXHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoBHYT", DbType="NVarChar(9)")]
		public string SoBHYT
		{
			get
			{
				return this._SoBHYT;
			}
			set
			{
				if ((this._SoBHYT != value))
				{
					this.OnSoBHYTChanging(value);
					this.SendPropertyChanging();
					this._SoBHYT = value;
					this.SendPropertyChanged("SoBHYT");
					this.OnSoBHYTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongTL", DbType="Float")]
		public System.Nullable<double> LuongTL
		{
			get
			{
				return this._LuongTL;
			}
			set
			{
				if ((this._LuongTL != value))
				{
					this.OnLuongTLChanging(value);
					this.SendPropertyChanging();
					this._LuongTL = value;
					this.SendPropertyChanged("LuongTL");
					this.OnLuongTLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThueTN", DbType="NVarChar(12)")]
		public string ThueTN
		{
			get
			{
				return this._ThueTN;
			}
			set
			{
				if ((this._ThueTN != value))
				{
					this.OnThueTNChanging(value);
					this.SendPropertyChanging();
					this._ThueTN = value;
					this.SendPropertyChanged("ThueTN");
					this.OnThueTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_KhenThuong", Storage="_KhenThuongs", ThisKey="MaCB", OtherKey="MaCB")]
		public EntitySet<KhenThuong> KhenThuongs
		{
			get
			{
				return this._KhenThuongs;
			}
			set
			{
				this._KhenThuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_KyLuat", Storage="_KyLuats", ThisKey="MaCB", OtherKey="MaCB")]
		public EntitySet<KyLuat> KyLuats
		{
			get
			{
				return this._KyLuats;
			}
			set
			{
				this._KyLuats.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_QuanHeGiaDinh", Storage="_QuanHeGiaDinhs", ThisKey="MaCB", OtherKey="MaCB")]
		public EntitySet<QuanHeGiaDinh> QuanHeGiaDinhs
		{
			get
			{
				return this._QuanHeGiaDinhs;
			}
			set
			{
				this._QuanHeGiaDinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_QuaTrinhCongTac", Storage="_QuaTrinhCongTacs", ThisKey="MaCB", OtherKey="MaCB")]
		public EntitySet<QuaTrinhCongTac> QuaTrinhCongTacs
		{
			get
			{
				return this._QuaTrinhCongTacs;
			}
			set
			{
				this._QuaTrinhCongTacs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_HoSoCanBo", Storage="_ChucVu", ThisKey="MaCV", OtherKey="MaCV", IsForeignKey=true, DeleteRule="CASCADE")]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaCV = value.MaCV;
					}
					else
					{
						this._MaCV = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HocHam_HoSoCanBo", Storage="_HocHam", ThisKey="MaHocHam", OtherKey="MaHocHam", IsForeignKey=true, DeleteRule="CASCADE")]
		public HocHam HocHam
		{
			get
			{
				return this._HocHam.Entity;
			}
			set
			{
				HocHam previousValue = this._HocHam.Entity;
				if (((previousValue != value) 
							|| (this._HocHam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HocHam.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._HocHam.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaHocHam = value.MaHocHam;
					}
					else
					{
						this._MaHocHam = default(string);
					}
					this.SendPropertyChanged("HocHam");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HopDongLaoDong_HoSoCanBo", Storage="_HopDongLaoDong", ThisKey="MasoHD", OtherKey="MasoHD", IsForeignKey=true, DeleteRule="CASCADE")]
		public HopDongLaoDong HopDongLaoDong
		{
			get
			{
				return this._HopDongLaoDong.Entity;
			}
			set
			{
				HopDongLaoDong previousValue = this._HopDongLaoDong.Entity;
				if (((previousValue != value) 
							|| (this._HopDongLaoDong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HopDongLaoDong.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._HopDongLaoDong.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MasoHD = value.MasoHD;
					}
					else
					{
						this._MasoHD = default(string);
					}
					this.SendPropertyChanged("HopDongLaoDong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TrinhDoChuyenMon_HoSoCanBo", Storage="_TrinhDoChuyenMon", ThisKey="MaTDCM", OtherKey="MaTDCM", IsForeignKey=true, DeleteRule="CASCADE")]
		public TrinhDoChuyenMon TrinhDoChuyenMon
		{
			get
			{
				return this._TrinhDoChuyenMon.Entity;
			}
			set
			{
				TrinhDoChuyenMon previousValue = this._TrinhDoChuyenMon.Entity;
				if (((previousValue != value) 
							|| (this._TrinhDoChuyenMon.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TrinhDoChuyenMon.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._TrinhDoChuyenMon.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaTDCM = value.MaTDCM;
					}
					else
					{
						this._MaTDCM = default(string);
					}
					this.SendPropertyChanged("TrinhDoChuyenMon");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Luong_HoSoCanBo", Storage="_Luong", ThisKey="MaLuong", OtherKey="MaLuong", IsForeignKey=true, DeleteRule="CASCADE")]
		public Luong Luong
		{
			get
			{
				return this._Luong.Entity;
			}
			set
			{
				Luong previousValue = this._Luong.Entity;
				if (((previousValue != value) 
							|| (this._Luong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Luong.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._Luong.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaLuong = value.MaLuong;
					}
					else
					{
						this._MaLuong = default(string);
					}
					this.SendPropertyChanged("Luong");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NgoaiNgu_HoSoCanBo", Storage="_NgoaiNgu", ThisKey="MaTDNN", OtherKey="MaTDNN", IsForeignKey=true, DeleteRule="CASCADE")]
		public NgoaiNgu NgoaiNgu
		{
			get
			{
				return this._NgoaiNgu.Entity;
			}
			set
			{
				NgoaiNgu previousValue = this._NgoaiNgu.Entity;
				if (((previousValue != value) 
							|| (this._NgoaiNgu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NgoaiNgu.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._NgoaiNgu.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaTDNN = value.MaTDNN;
					}
					else
					{
						this._MaTDNN = default(string);
					}
					this.SendPropertyChanged("NgoaiNgu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThamNien_HoSoCanBo", Storage="_ThamNien", ThisKey="MaTN", OtherKey="MaTN", IsForeignKey=true, DeleteRule="CASCADE")]
		public ThamNien ThamNien
		{
			get
			{
				return this._ThamNien.Entity;
			}
			set
			{
				ThamNien previousValue = this._ThamNien.Entity;
				if (((previousValue != value) 
							|| (this._ThamNien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ThamNien.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._ThamNien.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaTN = value.MaTN;
					}
					else
					{
						this._MaTN = default(string);
					}
					this.SendPropertyChanged("ThamNien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="To_HoSoCanBo", Storage="_To", ThisKey="MaTo", OtherKey="MaTo", IsForeignKey=true, DeleteRule="CASCADE")]
		public To To
		{
			get
			{
				return this._To.Entity;
			}
			set
			{
				To previousValue = this._To.Entity;
				if (((previousValue != value) 
							|| (this._To.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._To.Entity = null;
						previousValue.HoSoCanBos.Remove(this);
					}
					this._To.Entity = value;
					if ((value != null))
					{
						value.HoSoCanBos.Add(this);
						this._MaTo = value.MaTo;
					}
					else
					{
						this._MaTo = default(string);
					}
					this.SendPropertyChanged("To");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KhenThuongs(KhenThuong entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = this;
		}
		
		private void detach_KhenThuongs(KhenThuong entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = null;
		}
		
		private void attach_KyLuats(KyLuat entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = this;
		}
		
		private void detach_KyLuats(KyLuat entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = null;
		}
		
		private void attach_QuanHeGiaDinhs(QuanHeGiaDinh entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = this;
		}
		
		private void detach_QuanHeGiaDinhs(QuanHeGiaDinh entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = null;
		}
		
		private void attach_QuaTrinhCongTacs(QuaTrinhCongTac entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = this;
		}
		
		private void detach_QuaTrinhCongTacs(QuaTrinhCongTac entity)
		{
			this.SendPropertyChanging();
			entity.HoSoCanBo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhenThuong")]
	public partial class KhenThuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKhenThuong;
		
		private string _MaCB;
		
		private string _LyDoKhenThuong;
		
		private System.Nullable<System.DateTime> _NgayKhenThuong;
		
		private EntityRef<HoSoCanBo> _HoSoCanBo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhenThuongChanging(string value);
    partial void OnMaKhenThuongChanged();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnLyDoKhenThuongChanging(string value);
    partial void OnLyDoKhenThuongChanged();
    partial void OnNgayKhenThuongChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKhenThuongChanged();
    #endregion
		
		public KhenThuong()
		{
			this._HoSoCanBo = default(EntityRef<HoSoCanBo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhenThuong", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKhenThuong
		{
			get
			{
				return this._MaKhenThuong;
			}
			set
			{
				if ((this._MaKhenThuong != value))
				{
					this.OnMaKhenThuongChanging(value);
					this.SendPropertyChanging();
					this._MaKhenThuong = value;
					this.SendPropertyChanged("MaKhenThuong");
					this.OnMaKhenThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(15)")]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					if (this._HoSoCanBo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoKhenThuong", DbType="NVarChar(150)")]
		public string LyDoKhenThuong
		{
			get
			{
				return this._LyDoKhenThuong;
			}
			set
			{
				if ((this._LyDoKhenThuong != value))
				{
					this.OnLyDoKhenThuongChanging(value);
					this.SendPropertyChanging();
					this._LyDoKhenThuong = value;
					this.SendPropertyChanged("LyDoKhenThuong");
					this.OnLyDoKhenThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKhenThuong", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayKhenThuong
		{
			get
			{
				return this._NgayKhenThuong;
			}
			set
			{
				if ((this._NgayKhenThuong != value))
				{
					this.OnNgayKhenThuongChanging(value);
					this.SendPropertyChanging();
					this._NgayKhenThuong = value;
					this.SendPropertyChanged("NgayKhenThuong");
					this.OnNgayKhenThuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_KhenThuong", Storage="_HoSoCanBo", ThisKey="MaCB", OtherKey="MaCB", IsForeignKey=true, DeleteRule="CASCADE")]
		public HoSoCanBo HoSoCanBo
		{
			get
			{
				return this._HoSoCanBo.Entity;
			}
			set
			{
				HoSoCanBo previousValue = this._HoSoCanBo.Entity;
				if (((previousValue != value) 
							|| (this._HoSoCanBo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoCanBo.Entity = null;
						previousValue.KhenThuongs.Remove(this);
					}
					this._HoSoCanBo.Entity = value;
					if ((value != null))
					{
						value.KhenThuongs.Add(this);
						this._MaCB = value.MaCB;
					}
					else
					{
						this._MaCB = default(string);
					}
					this.SendPropertyChanged("HoSoCanBo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KyLuat")]
	public partial class KyLuat : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKyLuat;
		
		private string _MaCB;
		
		private string _LyDoKyLuat;
		
		private System.Nullable<System.DateTime> _NgayKyLuat;
		
		private string _HinhThucKyLuat;
		
		private EntityRef<HoSoCanBo> _HoSoCanBo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKyLuatChanging(string value);
    partial void OnMaKyLuatChanged();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnLyDoKyLuatChanging(string value);
    partial void OnLyDoKyLuatChanged();
    partial void OnNgayKyLuatChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKyLuatChanged();
    partial void OnHinhThucKyLuatChanging(string value);
    partial void OnHinhThucKyLuatChanged();
    #endregion
		
		public KyLuat()
		{
			this._HoSoCanBo = default(EntityRef<HoSoCanBo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKyLuat", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKyLuat
		{
			get
			{
				return this._MaKyLuat;
			}
			set
			{
				if ((this._MaKyLuat != value))
				{
					this.OnMaKyLuatChanging(value);
					this.SendPropertyChanging();
					this._MaKyLuat = value;
					this.SendPropertyChanged("MaKyLuat");
					this.OnMaKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(15)")]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					if (this._HoSoCanBo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LyDoKyLuat", DbType="NVarChar(150)")]
		public string LyDoKyLuat
		{
			get
			{
				return this._LyDoKyLuat;
			}
			set
			{
				if ((this._LyDoKyLuat != value))
				{
					this.OnLyDoKyLuatChanging(value);
					this.SendPropertyChanging();
					this._LyDoKyLuat = value;
					this.SendPropertyChanged("LyDoKyLuat");
					this.OnLyDoKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKyLuat", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayKyLuat
		{
			get
			{
				return this._NgayKyLuat;
			}
			set
			{
				if ((this._NgayKyLuat != value))
				{
					this.OnNgayKyLuatChanging(value);
					this.SendPropertyChanging();
					this._NgayKyLuat = value;
					this.SendPropertyChanged("NgayKyLuat");
					this.OnNgayKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhThucKyLuat", DbType="NVarChar(150)")]
		public string HinhThucKyLuat
		{
			get
			{
				return this._HinhThucKyLuat;
			}
			set
			{
				if ((this._HinhThucKyLuat != value))
				{
					this.OnHinhThucKyLuatChanging(value);
					this.SendPropertyChanging();
					this._HinhThucKyLuat = value;
					this.SendPropertyChanged("HinhThucKyLuat");
					this.OnHinhThucKyLuatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_KyLuat", Storage="_HoSoCanBo", ThisKey="MaCB", OtherKey="MaCB", IsForeignKey=true, DeleteRule="CASCADE")]
		public HoSoCanBo HoSoCanBo
		{
			get
			{
				return this._HoSoCanBo.Entity;
			}
			set
			{
				HoSoCanBo previousValue = this._HoSoCanBo.Entity;
				if (((previousValue != value) 
							|| (this._HoSoCanBo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoCanBo.Entity = null;
						previousValue.KyLuats.Remove(this);
					}
					this._HoSoCanBo.Entity = value;
					if ((value != null))
					{
						value.KyLuats.Add(this);
						this._MaCB = value.MaCB;
					}
					else
					{
						this._MaCB = default(string);
					}
					this.SendPropertyChanged("HoSoCanBo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Luong")]
	public partial class Luong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLuong;
		
		private System.Nullable<double> _LuongCB;
		
		private string _HesoLuong;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLuongChanging(string value);
    partial void OnMaLuongChanged();
    partial void OnLuongCBChanging(System.Nullable<double> value);
    partial void OnLuongCBChanged();
    partial void OnHesoLuongChanging(string value);
    partial void OnHesoLuongChanged();
    #endregion
		
		public Luong()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLuong", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLuong
		{
			get
			{
				return this._MaLuong;
			}
			set
			{
				if ((this._MaLuong != value))
				{
					this.OnMaLuongChanging(value);
					this.SendPropertyChanging();
					this._MaLuong = value;
					this.SendPropertyChanged("MaLuong");
					this.OnMaLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuongCB", DbType="Float")]
		public System.Nullable<double> LuongCB
		{
			get
			{
				return this._LuongCB;
			}
			set
			{
				if ((this._LuongCB != value))
				{
					this.OnLuongCBChanging(value);
					this.SendPropertyChanging();
					this._LuongCB = value;
					this.SendPropertyChanged("LuongCB");
					this.OnLuongCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HesoLuong", DbType="VarChar(10)")]
		public string HesoLuong
		{
			get
			{
				return this._HesoLuong;
			}
			set
			{
				if ((this._HesoLuong != value))
				{
					this.OnHesoLuongChanging(value);
					this.SendPropertyChanging();
					this._HesoLuong = value;
					this.SendPropertyChanged("HesoLuong");
					this.OnHesoLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Luong_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaLuong", OtherKey="MaLuong")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.Luong = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.Luong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NgoaiNgu")]
	public partial class NgoaiNgu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTDNN;
		
		private string _TenNN;
		
		private string _LoaiTD;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTDNNChanging(string value);
    partial void OnMaTDNNChanged();
    partial void OnTenNNChanging(string value);
    partial void OnTenNNChanged();
    partial void OnLoaiTDChanging(string value);
    partial void OnLoaiTDChanged();
    #endregion
		
		public NgoaiNgu()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTDNN", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTDNN
		{
			get
			{
				return this._MaTDNN;
			}
			set
			{
				if ((this._MaTDNN != value))
				{
					this.OnMaTDNNChanging(value);
					this.SendPropertyChanging();
					this._MaTDNN = value;
					this.SendPropertyChanged("MaTDNN");
					this.OnMaTDNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNN", DbType="NVarChar(50)")]
		public string TenNN
		{
			get
			{
				return this._TenNN;
			}
			set
			{
				if ((this._TenNN != value))
				{
					this.OnTenNNChanging(value);
					this.SendPropertyChanging();
					this._TenNN = value;
					this.SendPropertyChanged("TenNN");
					this.OnTenNNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiTD", DbType="NVarChar(50)")]
		public string LoaiTD
		{
			get
			{
				return this._LoaiTD;
			}
			set
			{
				if ((this._LoaiTD != value))
				{
					this.OnLoaiTDChanging(value);
					this.SendPropertyChanging();
					this._LoaiTD = value;
					this.SendPropertyChanged("LoaiTD");
					this.OnLoaiTDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NgoaiNgu_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaTDNN", OtherKey="MaTDNN")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.NgoaiNgu = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.NgoaiNgu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuanHeGiaDinh")]
	public partial class QuanHeGiaDinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaCB;
		
		private string _TenQuanHe;
		
		private string _HoTen;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private string _NgheNhiep;
		
		private string _DiaChi;
		
		private EntityRef<HoSoCanBo> _HoSoCanBo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnTenQuanHeChanging(string value);
    partial void OnTenQuanHeChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnNgheNhiepChanging(string value);
    partial void OnNgheNhiepChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    #endregion
		
		public QuanHeGiaDinh()
		{
			this._HoSoCanBo = default(EntityRef<HoSoCanBo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					if (this._HoSoCanBo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenQuanHe", DbType="NVarChar(150)")]
		public string TenQuanHe
		{
			get
			{
				return this._TenQuanHe;
			}
			set
			{
				if ((this._TenQuanHe != value))
				{
					this.OnTenQuanHeChanging(value);
					this.SendPropertyChanging();
					this._TenQuanHe = value;
					this.SendPropertyChanged("TenQuanHe");
					this.OnTenQuanHeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50)")]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgheNhiep", DbType="NVarChar(150)")]
		public string NgheNhiep
		{
			get
			{
				return this._NgheNhiep;
			}
			set
			{
				if ((this._NgheNhiep != value))
				{
					this.OnNgheNhiepChanging(value);
					this.SendPropertyChanging();
					this._NgheNhiep = value;
					this.SendPropertyChanged("NgheNhiep");
					this.OnNgheNhiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(250)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_QuanHeGiaDinh", Storage="_HoSoCanBo", ThisKey="MaCB", OtherKey="MaCB", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HoSoCanBo HoSoCanBo
		{
			get
			{
				return this._HoSoCanBo.Entity;
			}
			set
			{
				HoSoCanBo previousValue = this._HoSoCanBo.Entity;
				if (((previousValue != value) 
							|| (this._HoSoCanBo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoCanBo.Entity = null;
						previousValue.QuanHeGiaDinhs.Remove(this);
					}
					this._HoSoCanBo.Entity = value;
					if ((value != null))
					{
						value.QuanHeGiaDinhs.Add(this);
						this._MaCB = value.MaCB;
					}
					else
					{
						this._MaCB = default(string);
					}
					this.SendPropertyChanged("HoSoCanBo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QuaTrinhCongTac")]
	public partial class QuaTrinhCongTac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MaCB;
		
		private string _MaTo;
		
		private string _MaCV;
		
		private string _QuaTrinhCongTac1;
		
		private System.Nullable<System.DateTime> _TuNgay;
		
		private System.Nullable<System.DateTime> _DenNgay;
		
		private System.Nullable<System.DateTime> _NgayChuyenCT;
		
		private EntityRef<HoSoCanBo> _HoSoCanBo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMaCBChanging(string value);
    partial void OnMaCBChanged();
    partial void OnMaToChanging(string value);
    partial void OnMaToChanged();
    partial void OnMaCVChanging(string value);
    partial void OnMaCVChanged();
    partial void OnQuaTrinhCongTac1Changing(string value);
    partial void OnQuaTrinhCongTac1Changed();
    partial void OnTuNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnTuNgayChanged();
    partial void OnDenNgayChanging(System.Nullable<System.DateTime> value);
    partial void OnDenNgayChanged();
    partial void OnNgayChuyenCTChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayChuyenCTChanged();
    #endregion
		
		public QuaTrinhCongTac()
		{
			this._HoSoCanBo = default(EntityRef<HoSoCanBo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCB", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string MaCB
		{
			get
			{
				return this._MaCB;
			}
			set
			{
				if ((this._MaCB != value))
				{
					if (this._HoSoCanBo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCBChanging(value);
					this.SendPropertyChanging();
					this._MaCB = value;
					this.SendPropertyChanged("MaCB");
					this.OnMaCBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTo", DbType="VarChar(15)")]
		public string MaTo
		{
			get
			{
				return this._MaTo;
			}
			set
			{
				if ((this._MaTo != value))
				{
					this.OnMaToChanging(value);
					this.SendPropertyChanging();
					this._MaTo = value;
					this.SendPropertyChanged("MaTo");
					this.OnMaToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCV", DbType="VarChar(15)")]
		public string MaCV
		{
			get
			{
				return this._MaCV;
			}
			set
			{
				if ((this._MaCV != value))
				{
					this.OnMaCVChanging(value);
					this.SendPropertyChanging();
					this._MaCV = value;
					this.SendPropertyChanged("MaCV");
					this.OnMaCVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="QuaTrinhCongTac", Storage="_QuaTrinhCongTac1", DbType="NVarChar(250)")]
		public string QuaTrinhCongTac1
		{
			get
			{
				return this._QuaTrinhCongTac1;
			}
			set
			{
				if ((this._QuaTrinhCongTac1 != value))
				{
					this.OnQuaTrinhCongTac1Changing(value);
					this.SendPropertyChanging();
					this._QuaTrinhCongTac1 = value;
					this.SendPropertyChanged("QuaTrinhCongTac1");
					this.OnQuaTrinhCongTac1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuNgay", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TuNgay
		{
			get
			{
				return this._TuNgay;
			}
			set
			{
				if ((this._TuNgay != value))
				{
					this.OnTuNgayChanging(value);
					this.SendPropertyChanging();
					this._TuNgay = value;
					this.SendPropertyChanged("TuNgay");
					this.OnTuNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DenNgay", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> DenNgay
		{
			get
			{
				return this._DenNgay;
			}
			set
			{
				if ((this._DenNgay != value))
				{
					this.OnDenNgayChanging(value);
					this.SendPropertyChanging();
					this._DenNgay = value;
					this.SendPropertyChanged("DenNgay");
					this.OnDenNgayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayChuyenCT", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NgayChuyenCT
		{
			get
			{
				return this._NgayChuyenCT;
			}
			set
			{
				if ((this._NgayChuyenCT != value))
				{
					this.OnNgayChuyenCTChanging(value);
					this.SendPropertyChanging();
					this._NgayChuyenCT = value;
					this.SendPropertyChanged("NgayChuyenCT");
					this.OnNgayChuyenCTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoCanBo_QuaTrinhCongTac", Storage="_HoSoCanBo", ThisKey="MaCB", OtherKey="MaCB", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public HoSoCanBo HoSoCanBo
		{
			get
			{
				return this._HoSoCanBo.Entity;
			}
			set
			{
				HoSoCanBo previousValue = this._HoSoCanBo.Entity;
				if (((previousValue != value) 
							|| (this._HoSoCanBo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoCanBo.Entity = null;
						previousValue.QuaTrinhCongTacs.Remove(this);
					}
					this._HoSoCanBo.Entity = value;
					if ((value != null))
					{
						value.QuaTrinhCongTacs.Add(this);
						this._MaCB = value.MaCB;
					}
					else
					{
						this._MaCB = default(string);
					}
					this.SendPropertyChanged("HoSoCanBo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThamNien")]
	public partial class ThamNien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTN;
		
		private string _ThamNien1;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTNChanging(string value);
    partial void OnMaTNChanged();
    partial void OnThamNien1Changing(string value);
    partial void OnThamNien1Changed();
    #endregion
		
		public ThamNien()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTN", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTN
		{
			get
			{
				return this._MaTN;
			}
			set
			{
				if ((this._MaTN != value))
				{
					this.OnMaTNChanging(value);
					this.SendPropertyChanging();
					this._MaTN = value;
					this.SendPropertyChanged("MaTN");
					this.OnMaTNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="ThamNien", Storage="_ThamNien1", DbType="NVarChar(50)")]
		public string ThamNien1
		{
			get
			{
				return this._ThamNien1;
			}
			set
			{
				if ((this._ThamNien1 != value))
				{
					this.OnThamNien1Changing(value);
					this.SendPropertyChanging();
					this._ThamNien1 = value;
					this.SendPropertyChanged("ThamNien1");
					this.OnThamNien1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ThamNien_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaTN", OtherKey="MaTN")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.ThamNien = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.ThamNien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[To]")]
	public partial class To : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaTo;
		
		private string _TenTo;
		
		private EntitySet<HoSoCanBo> _HoSoCanBos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaToChanging(string value);
    partial void OnMaToChanged();
    partial void OnTenToChanging(string value);
    partial void OnTenToChanged();
    #endregion
		
		public To()
		{
			this._HoSoCanBos = new EntitySet<HoSoCanBo>(new Action<HoSoCanBo>(this.attach_HoSoCanBos), new Action<HoSoCanBo>(this.detach_HoSoCanBos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTo", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaTo
		{
			get
			{
				return this._MaTo;
			}
			set
			{
				if ((this._MaTo != value))
				{
					this.OnMaToChanging(value);
					this.SendPropertyChanging();
					this._MaTo = value;
					this.SendPropertyChanged("MaTo");
					this.OnMaToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTo", DbType="NVarChar(50)")]
		public string TenTo
		{
			get
			{
				return this._TenTo;
			}
			set
			{
				if ((this._TenTo != value))
				{
					this.OnTenToChanging(value);
					this.SendPropertyChanging();
					this._TenTo = value;
					this.SendPropertyChanged("TenTo");
					this.OnTenToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="To_HoSoCanBo", Storage="_HoSoCanBos", ThisKey="MaTo", OtherKey="MaTo")]
		public EntitySet<HoSoCanBo> HoSoCanBos
		{
			get
			{
				return this._HoSoCanBos;
			}
			set
			{
				this._HoSoCanBos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.To = this;
		}
		
		private void detach_HoSoCanBos(HoSoCanBo entity)
		{
			this.SendPropertyChanging();
			entity.To = null;
		}
	}
}
#pragma warning restore 1591
