<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyNhanSu_Hai" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=QuanLyNhanSu_Hai;Integrated Security=True" SettingsObjectName="QuanLyNhanSu_Hai.Properties.Settings" SettingsPropertyName="QuanLyNhanSu_HaiConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChucVu" Member="ChucVus">
    <Type Name="ChucVu">
      <Column Name="MaCV" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenChucVu" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ChucVu_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaCV" OtherKey="MaCV" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.TrinhDoChuyenMon" Member="TrinhDoChuyenMons">
    <Type Name="TrinhDoChuyenMon">
      <Column Name="MaTDCM" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NganhDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiHinhDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TruongDT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NienKhoa" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Association Name="TrinhDoChuyenMon_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaTDCM" OtherKey="MaTDCM" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.DanToc" Member="DanTocs">
    <Type Name="DanToc">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DanToc" Member="DanToc1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HeThong" Member="HeThongs">
    <Type Name="HeThong">
      <Column Name="Username" Type="System.String" DbType="NVarChar(25) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="Access" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Update]" Member="Update" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Manage" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Discription" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HocHam" Member="HocHams">
    <Type Name="HocHam">
      <Column Name="MaHocHam" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HocHam" Member="HocHam1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="HocHam_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaHocHam" OtherKey="MaHocHam" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.HopDongLaoDong" Member="HopDongLaoDongs">
    <Type Name="HopDongLaoDong">
      <Column Name="MasoHD" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="NgayHD" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="LoaiHD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayBD" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayKT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayXL" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SoBHYT" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="SoBHXH" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Association Name="HopDongLaoDong_HoSoCanBo" Member="HoSoCanBos" ThisKey="MasoHD" OtherKey="MasoHD" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.HoSoCanBo" Member="HoSoCanBos">
    <Type Name="HoSoCanBo">
      <Column Name="MaCB" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Noisinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="QueQuan" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanToc" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="MaTN" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayChuyenCT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="QuaTrinhCongTac" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="MaTo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaTDCM" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="SoCMND" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayCap" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NoiCap" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SoDT" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DangVien" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SoTheDang" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayVaoDang" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NoiVaoDang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaTDNN" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaHocHam" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="NgayNhanHH" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="MaLuong" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MasoHD" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LoaiHD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayHD" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayBD" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayKT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayXL" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="SoBHXH" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="SoBHYT" Type="System.String" DbType="NVarChar(9)" CanBeNull="true" />
      <Column Name="LuongTL" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ThueTN" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Association Name="HoSoCanBo_KhenThuong" Member="KhenThuongs" ThisKey="MaCB" OtherKey="MaCB" Type="KhenThuong" />
      <Association Name="HoSoCanBo_KyLuat" Member="KyLuats" ThisKey="MaCB" OtherKey="MaCB" Type="KyLuat" />
      <Association Name="HoSoCanBo_QuanHeGiaDinh" Member="QuanHeGiaDinhs" ThisKey="MaCB" OtherKey="MaCB" Type="QuanHeGiaDinh" />
      <Association Name="HoSoCanBo_QuaTrinhCongTac" Member="QuaTrinhCongTacs" ThisKey="MaCB" OtherKey="MaCB" Type="QuaTrinhCongTac" />
      <Association Name="ChucVu_HoSoCanBo" Member="ChucVu" ThisKey="MaCV" OtherKey="MaCV" Type="ChucVu" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="HocHam_HoSoCanBo" Member="HocHam" ThisKey="MaHocHam" OtherKey="MaHocHam" Type="HocHam" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="HopDongLaoDong_HoSoCanBo" Member="HopDongLaoDong" ThisKey="MasoHD" OtherKey="MasoHD" Type="HopDongLaoDong" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="TrinhDoChuyenMon_HoSoCanBo" Member="TrinhDoChuyenMon" ThisKey="MaTDCM" OtherKey="MaTDCM" Type="TrinhDoChuyenMon" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Luong_HoSoCanBo" Member="Luong" ThisKey="MaLuong" OtherKey="MaLuong" Type="Luong" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="NgoaiNgu_HoSoCanBo" Member="NgoaiNgu" ThisKey="MaTDNN" OtherKey="MaTDNN" Type="NgoaiNgu" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ThamNien_HoSoCanBo" Member="ThamNien" ThisKey="MaTN" OtherKey="MaTN" Type="ThamNien" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="To_HoSoCanBo" Member="To" ThisKey="MaTo" OtherKey="MaTo" Type="To" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.KhenThuong" Member="KhenThuongs">
    <Type Name="KhenThuong">
      <Column Name="MaKhenThuong" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCB" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LyDoKhenThuong" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayKhenThuong" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="HoSoCanBo_KhenThuong" Member="HoSoCanBo" ThisKey="MaCB" OtherKey="MaCB" Type="HoSoCanBo" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.KyLuat" Member="KyLuats">
    <Type Name="KyLuat">
      <Column Name="MaKyLuat" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCB" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="LyDoKyLuat" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NgayKyLuat" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="HinhThucKyLuat" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Association Name="HoSoCanBo_KyLuat" Member="HoSoCanBo" ThisKey="MaCB" OtherKey="MaCB" Type="HoSoCanBo" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Luong" Member="Luongs">
    <Type Name="Luong">
      <Column Name="MaLuong" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="LuongCB" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="HesoLuong" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Luong_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaLuong" OtherKey="MaLuong" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.NgoaiNgu" Member="NgoaiNgus">
    <Type Name="NgoaiNgu">
      <Column Name="MaTDNN" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenNN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LoaiTD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="NgoaiNgu_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaTDNN" OtherKey="MaTDNN" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.QuanHeGiaDinh" Member="QuanHeGiaDinhs">
    <Type Name="QuanHeGiaDinh">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaCB" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenQuanHe" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgaySinh" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgheNhiep" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="HoSoCanBo_QuanHeGiaDinh" Member="HoSoCanBo" ThisKey="MaCB" OtherKey="MaCB" Type="HoSoCanBo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QuaTrinhCongTac" Member="QuaTrinhCongTacs">
    <Type Name="QuaTrinhCongTac">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MaCB" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="MaTo" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="MaCV" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="QuaTrinhCongTac" Member="QuaTrinhCongTac1" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="TuNgay" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="DenNgay" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="NgayChuyenCT" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Association Name="HoSoCanBo_QuaTrinhCongTac" Member="HoSoCanBo" ThisKey="MaCB" OtherKey="MaCB" Type="HoSoCanBo" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThamNien" Member="ThamNiens">
    <Type Name="ThamNien">
      <Column Name="MaTN" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThamNien" Member="ThamNien1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="ThamNien_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaTN" OtherKey="MaTN" Type="HoSoCanBo" />
    </Type>
  </Table>
  <Table Name="dbo.[To]" Member="Tos">
    <Type Name="To">
      <Column Name="MaTo" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenTo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="To_HoSoCanBo" Member="HoSoCanBos" ThisKey="MaTo" OtherKey="MaTo" Type="HoSoCanBo" />
    </Type>
  </Table>
</Database>